project:
  type: website

execute:
  echo: true
  warning: false

website:
  title: "From R User to R Programmer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pre-reqs.qmd
        text: Prerequisites
      - href: schedule.qmd
        text: Schedule
      - text: Materials
        menu:
        - text: ---
        - text: Functions
        - text: ---
        - text: "ðŸ‘‹ & Functions Part 1"
          href: 01-functions-01.qmd
        - text: "Functions Part 2"
          href: 02-functions-02.qmd
        - text: ---
        - text: Iteration
        - text: ---
        - text: "Iteration Part 1"
          href: 03-iteration-01.qmd
        - text: "Iteration Part 2"
          href: 04-iteration-02.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

comments:
  hypothesis: true
  
editor: visual

